---
- name: EDA lab
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://10.0.151.107:8080/edvige/rest/entries
        delay: 10
  rules:
    - name: Restart Wildfly if url is not reachable
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "Restart Wildfly"
          organization: "Jug-Grenoble"
