---
- name: Flush Db if idled connections are detected
  hosts: wildfly
  sources:
    - ansible.eda.journald:
        match: ALL

  rules:
    - name: Match all on journald
      condition: event.journald.message is search("EDVIGE App is broken", ignorecase=false)
      action:
        run_job_template:
          name: "Flush Idle Db"
          organization: "Jug-Grenoble"
